### ISSUE TITLE
It's better to use bcrypt instead of md5

### ISSUE THREAD

**Issue by mohsenyz** [Moeinh77/AndroidWorkShop#1]
Hi, it's better to migrate from md5 to bcrypt. MD5 is really fast with a lot of security issues and shouldn't be used for passwords, also you haven't used salt, so I think it's a good idea to use bcrypt algorithm 
Thanks

**Comment by Moeinh77** [comment]
@mphj Hello,Thanks for reaching out 
This repository is created for an Android workshop and just to represent how client and server interact so as a result it wasn't really focused on the security.
But ofcourse you are right and I will fix this in near future .

**Comment by Moeinh77** [comment]
> Hi, it's better to migrate from md5 to bcrypt. MD5 is really fast with a lot of security issues and shouldn't be used for passwords, also you haven't used salt, so I think it's a good idea to use bcrypt algorithm
> Thanks

@mphj Hello,Thanks for reaching out
This repository is created for an Android workshop and just to represent how client and server interact so as a result it wasn't really focused on the security.
But ofcourse you are right and I will fix this in near future .
